[build-system]
requires = ["setuptools", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"


[tool.setuptools_scm]
write_to = "napari_organoid_counter/_version.py"

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
